version: '3'

services:
  app:
    image: bliptrip/semantic-segmentation-editor:latest
    volumes:
      - "${SSE_IMAGES}:/root/sse-images:rw"
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      METEOR_SETTINGS: ${METEOR_SETTINGS}

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - "${MONGODB_PATH}:/data/db"
