#Targets for installing/uninstalling sse.service from systemd

install:
	sudo cp sse.service /lib/systemd/system/

enable:
	sudo systemctl enable sse.service

disable:
	sudo systemctl disable sse.service

start:
	sudo systemctl start sse.service

stop:
	sudo systemctl stop sse.service

restart:
	sudo systemctl restart sse.service
